config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest

  resources :files, only: [:index, :show, :new, :create, :update, :destroy] do
    post :download, on: :member
  end
  resource :profile, except: [:destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :uploads, only: [:show, :create, :destroy] do
    post :download, on: :member
  end
  resource :upload_key, only: [:create]

  root "files#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/upload.rb
# frozen_string_literal: true

class Upload < ApplicationRecord
  attr_reader :expires

  has_one_attached :file
  has_secure_token

  validates :file, attached: true
  validate :validate_and_store_expiration_string

  scope :expired, lambda {
    where(expires_at: ...Time.zone.now).or(
      Upload.where("(download_limit IS NOT NULL AND download_limit > download_count)")
    )
  }

  def to_param
    token
  end

  def expired?
    expires_at&.past? || (download_limit.present? && download_limit > download_count)
  end

  def expires=(value)
    self.expires_at = nil
    @expires = value
  end

  private

  # custom validation
  def validate_and_store_expiration_string
    return if expires.blank?

    self.expires_at = ActiveSupport::Duration.parse(expires.upcase.strip).from_now
  rescue ActiveSupport::Duration::ISO8601Parser::ParsingError
    self.expires_at = nil
    errors.add(:base, "Expires is not a valid ISO 8601 string")
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_secure_token
  has_secure_token :upload_key, length: 36
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern

  include Pagy::Backend

  around_action :switch_locale
  before_action :authenticate_user!

  helper_method :user_signed_in?, :current_user

  private

  def require_no_user
    redirect_to root_path if User.any?
  end

  def require_user
    redirect_to new_profile_path unless User.any?
  end

  def sign_in(user)
    cookies.signed[:signin] = { value: user.token, httponly: true, same_site: :lax, expires: 20.minutes }
  end

  def sign_out
    cookies.delete(:signin)
    reset_session
  end

  def user_signed_in?
    @user_signed_in ||= User.find_by(token: cookies.signed[:signin])
  end

  def current_user
    @user_signed_in
  end

  def authenticate_user!
    if user_signed_in?
      sign_in(@user_signed_in)
    else
      redirect_to new_session_path
    end
  end

  def switch_locale(&action)
    locale = ENV["FILEZ_LOCALE"].presence || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/files_controller.rb
# frozen_string_literal: true

class FilesController < ApplicationController
  before_action :fetch_upload, only: [:show, :update, :destroy, :download]

  def index
    @pagy, @uploads = pagy(Upload.order(created_at: :desc).with_attached_file, items: 30)
  end

  def show
    @share_url = upload_url(@upload.signed_id)
  end

  def new
    @upload = Upload.new
  end

  def create
    @upload = Upload.new(upload_params)
    if @upload.save
      respond_to do |format|
        format.turbo_stream do
          flash[:notice] = translate("flash.file_uploaded")
          render turbo_stream: turbo_stream.action(:redirect, files_path)
        end
        format.html do
          redirect_to files_path, notice: translate("flash.file_uploaded")
        end
      end
    else
      redirect_to files_path, alert: @upload.errors.full_sentences.join
    end
  end

  def update
    if @upload.update(edit_upload_params)
      redirect_to file_path(@upload)
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @upload.destroy!
    redirect_to files_path, status: :see_other
  end

  def download
    send_data @upload.file.download, type: @upload.file.content_type, filename: @upload.file.filename.to_s
  end

  private

  def fetch_upload
    @upload = Upload.find_by!(token: params[:id])
  end

  def upload_params
    params.require(:upload).permit(:file)
  end

  def edit_upload_params
    params.require(:upload).permit(:private)
  end
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  def show
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :require_no_user, only: [:new, :create]
  before_action :require_user, only: [:edit, :show, :update]
  skip_before_action :authenticate_user!, only: [:new, :create]

  def show
  end

  def new
    @user = User.new
  end

  def edit
    @user = @user_signed_in
  end

  def create
    @user = User.new(user_password_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: translate("flash.setup_complete") }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = @user_signed_in

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to edit_profile_path, notice: translate("flash.settings_updated") }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :authenticate_user!

  before_action :require_user

  def new
  end

  def create
    user = User.take

    if user.authenticate(params[:password])
      sign_in(user)
      redirect_to root_path
    else
      flash.now.alert = translate("flash.incorrect_password")
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    sign_out
    redirect_to root_path, status: :see_other
  end
end

app/controllers/upload_keys_controller.rb
# frozen_string_literal: true

class UploadKeysController < ApplicationController
  def create
    @user_signed_in.regenerate_upload_key

    redirect_to edit_profile_path, notice: translate("flash.upload_key_regenerated")
  end
end

app/controllers/uploads_controller.rb
# frozen_string_literal: true

class UploadsController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:create]

  before_action :fetch_upload, only: [:show, :download]

  def show
  end

  def create
    @user = User.take
    if authenticate_with_http_token { |token, _options| token == @user.upload_key }
      @upload = Upload.new(upload_params)
      @upload.file = params[:file]
      if @upload.save
        render json: {
          status: 201,
          share_url: upload_url(@upload.signed_id),
          url: file_url(@upload)
        }, status: :created
      else
        render json: { status: 422, errors: @upload.errors.full_sentences }, status: :unprocessable_entity
      end
    else
      render json: { status: 401, errors: ["Not authorized"] }, status: :unauthorized
    end
  end

  def download
    @upload.increment!(:download_count, touch: true) # rubocop:disable Rails/SkipsModelValidations
    send_data @upload.file.download, type: @upload.file.content_type, filename: @upload.file.filename.to_s
  end

  private

  def fetch_upload
    @upload_sid = params[:id]
    @upload = Upload.find_signed(@upload_sid)

    raise ActiveRecord::RecordNotFound if @upload.blank? || @upload.expired?
  end

  def upload_params
    {
      download_count: params[:limit],
      expires: params[:expires]
    }.compact_blank
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/profiles_helper.rb
# frozen_string_literal: true

module ProfilesHelper
end

app/views/files/index.html.erb
<div class="sm:mt-10 p-4 bg-white sm:mx-auto sm:rounded-md">
  <%= render partial: "shared/nav" %>

  <div class="sm:flex sm:justify-end">
    <div></div>
    <%= link_to "New Upload", new_file_path, data: { turbo_frame: :modal }, class: "button-primary" %>
  </div>

  <table class="table-auto w-full">
    <tbody class="divide-y-2">
      <% @uploads.each do |upload| %>
        <tr class="leading-10">
          <td><%= link_to upload.file.filename, file_path(upload), class: "underline" %></td>
          <td class="whitespace-nowrap hidden sm:table-cell"><%= upload.file.content_type %></td>
          <td class="whitespace-nowrap hidden sm:table-cell"><%= number_to_human_size(upload.file.byte_size) %></td>
          <td class="whitespace-nowrap hidden sm:table-cell"><%= upload.created_at.to_date.to_fs(:rfc822) %></td>
          <td class="whitespace-nowrap">
            <div class="flex justify-end space-x-3">
              <%= link_to "👁️", file_path(upload), title: translate("tooltip.details") %>
              <%= button_to "💾", download_file_path(upload), title: translate("tooltip.download") %>
              <%= button_to "🗑️", file_path(upload), method: :delete, title: translate("tooltip.delete"), data: { turbo_confirm: "Are you sure you want to delete this file?" } %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="mt-4"><%== pagy_nav(@pagy) %></div>
</div>

app/views/files/new.html.erb
<%= render 'layouts/turbo_dialog' do %>
  <%= form_with model: @upload, url: files_path, class: "flex justify-between" do |form| %>
    <%= form.label :file, class: "block sm:inline-block font-semibold text-blue-600 rounded-lg border border-dashed border-gray-900 p-2" do %>
      <%= form.file_field :file, required: true, class: "w-auto" %>
    <% end %>
    <%= form.submit class: "button-primary" %>
  <% end %>
<% end %>

app/views/files/show.html.erb
<% content_for :title, "File Details" %>

<div class="sm:mt-10 p-4 bg-white sm:mx-auto sm:w-full sm:max-w-lg sm:rounded-md">
  <%= render partial: "shared/nav" %>
  <div class="space-y-4">
    <h1><%= @upload.file.filename %></h1>
    <div>Type: <%= @upload.file.content_type %></div>
    <div>Size: <%= number_to_human_size(@upload.file.byte_size) %></div>
    <%= button_to "Download", download_file_path(@upload), class: "button-primary button-full", form: { data: { turbo: false } } %>
  </div>

  <div class="my-4 p-4 space-y-4 border border-blue-400 rounded-md">
    <%= tag.div class: "relative mt-2 rounded-md shadow-sm",
      data: {
        controller: "clipboard",
        clipboard_text_value: @share_url
      } do %>
      <%= text_field_tag :share_url, @share_url, autocomplete: "off", class:"textfield w-full pr-20" %>
      <div class="absolute inset-y-0 right-0 flex items-center">
        <%= button_tag "Copy", class: "h-full py-0 button-primary sm:text-sm", data: { action: "click->clipboard#copy", clipboard_target: "button" } %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_turbo_dialog.html.erb
<%= turbo_frame_tag :modal do %>
  <dialog data-controller="dialog"
          data-action="click->dialog#clickOutside"
          class="backdrop:bg-gray-400 backdrop:bg-opacity-90 z-10 rounded-md border-4 w-full md:w-2/3 mt-24">
    <div class="p-8">
      <div class="flex justify-end mb-4">
        <button class="button-primary" data-action="dialog#close">Close</button>
      </div>

      <%= yield %>

    </div>
  </dialog>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Filez" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-blue-500">
    <%= turbo_frame_tag :modal %>
    <% if alert.present? %>
      <aside data-controller="dismiss" data-dismiss-target="content" data-action="click->dismiss#close" class="cursor-pointer w-full fixed bottom-0 z-50 bg-red-500 px-4 py-2 text-white transition hover:bg-red-600">
        <div class="text-center font-bold"><%= alert %></div>
      </aside>
    <% end %>
    <% if notice.present? %>
      <aside data-controller="dismiss" data-dismiss-target="content" data-action="click->dismiss#close" class="cursor-pointer w-full fixed bottom-0 z-50 bg-green-500 px-4 py-2 text-white transition hover:bg-green-600">
        <div class="text-center font-bold"><%= notice %></div>
      </aside>
    <% end %>
    <main class="mx-0 sm:mx-4">
      <%= yield %>
    </main>
  </body>
</html>

app/views/profiles/edit.html.erb
<% content_for :title, "Edit Settings" %>

<div class="sm:mt-10 p-4 bg-white sm:mx-auto sm:w-full sm:max-w-lg sm:rounded-md">
  <%= render partial: "shared/nav" %>
  <%= form_with model: @user, url: profile_path do |form| %>
    <div class="space-y-4">
      <h1>Edit Settings</h1>
      <% if @user.errors.any? %>
        <div class="text-red-600">
          <ul>
            <% @user.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= form.label :password, class: "block" %>
        <%= form.password_field :password, autocomplete: "new-password", class: "textfield w-full" %>
      </div>

      <div>
        <%= form.label :password_confirmation, class: "block" %>
        <%= form.password_field :password_confirmation, autocomplete: "new-password", class: "textfield w-full" %>
      </div>

      <div>
        <%= form.submit "Update", class: "button-primary button-full" %>
      </div>
    </div>
  <% end %>

  <hr />

  <div class="space-y-2">
    <h1>Direct Upload</h1>

    <div>
      <%= label_tag :upload_key, nil, { class: "block" } %>
      <%= tag.div class: "relative rounded-md shadow-sm",
        data: {
          controller: "clipboard",
          clipboard_text_value: current_user.upload_key
        } do %>
        <%= text_field_tag :upload_key, current_user.upload_key, autocomplete: "off", class:"textfield w-full pr-20" %>
        <div class="absolute inset-y-0 right-0 flex items-center">
          <%= button_tag "Copy", class: "h-full py-0 button-primary sm:text-sm", data: { action: "click->clipboard#copy", clipboard_target: "button" } %>
        </div>
      <% end %>
    </div>

    <%= button_to "Regenerate", upload_key_path, class: "button-primary button-full" %>
  </div>

  <hr />

  <div class="space-y-2">
    <div>
      <h4>CURL Example:</h4>
      <div class="font-mono whitespace-pre-line overflow-x-scroll">$ curl -i -X POST \
        -H "Authorization: Bearer UPLOAD_KEY" \
        -F file=@../path/to/file.txt \
        <%= request.base_url %>/uploads
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<% content_for :title, "User Setup" %>

<%= form_with model: @user, url: profile_path, class: "sm:mt-10 p-4 bg-white sm:mx-auto sm:w-full sm:max-w-lg sm:rounded-md" do |form| %>
  <div class="space-y-4">
    <h1>User Setup</h1>
    <% if @user.errors.any? %>
      <div class="text-red-600">
        <h3>Could not set password</h3>

        <ul>
          <% @user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="space-y-2">
      <%= form.label :password, class: "block" %>
      <%= form.password_field :password, class: "textfield w-full", autocomplete: "new-password" %>
    </div>

    <div class="space-y-2">
      <%= form.label :password_confirmation, class: "block" %>
      <%= form.password_field :password_confirmation, class: "textfield w-full", autocomplete: "new-password" %>
    </div>

    <div>
      <%= form.submit "Set Password", class: "button-primary button-full" %>
    </div>
  </div>
<% end %>

app/views/shared/_nav.html.erb
  <nav class="flex items-center space-x-4">
    <%= link_to "All Files", files_path, class: "underline text-blue-600 text-sm" %>
    <%= link_to "Settings", edit_profile_path, class: "underline text-blue-600 text-sm" %>
    <%= button_to "Sign out", session_path, method: :delete, class: "underline text-blue-600 text-sm", form: { data: { turbo_confirm: "Are you sure?" } } %>
  </nav>

app/views/uploads/show.html.erb
<% content_for :title, "File Details" %>

<div class="sm:mt-10 p-4 bg-white sm:mx-auto sm:w-full sm:max-w-lg sm:rounded-md">
  <div class="space-y-4">
    <h1><%= @upload.file.filename %></h1>
    <div>Type: <%= @upload.file.content_type %></div>
    <div>Size: <%= number_to_human_size(@upload.file.byte_size) %></div>
    <%= button_to "Download", download_upload_path(@upload_sid), class: "button-primary button-full", form: { data: { turbo: false } } %>
  </div>
</div>